sudo: required

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.4
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=6.*"
    elif [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
  - composer install
  - nvm install --lts
  - nvm use --lts
  - npm install -g yarn
  - npm install -g webpack
  - yarn install

script:
  - ./vendor/bin/phpcs -s --standard=phpcs.ruleset.xml
  - phpunit
  - yarn run build
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: sh bin/deploy.sh
  on:
    branch: master
    php: 7.0
