sudo: required

language: php

services: mysql

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.4
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then
      composer global require "phpunit/phpunit=^7"
    else
      composer global require "phpunit/phpunit=^4"
    fi
  - |
  - composer install
  - nvm install --lts
  - nvm use --lts
  - npm install -g yarn
  - npm install -g webpack
  - yarn install

script:
  - ./vendor/bin/phpcs -s --standard=phpcs.ruleset.xml
  - phpunit
  - yarn run build
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: sh bin/deploy.sh
  on:
    branch: master
    php: 7.1
